#!/usr/bin/env python3 

import sys
import subprocess
from pathlib import Path

def run():
    if len(sys.argv) < 2:
        print("Using crn <file>")
        return

    file_path = Path(sys.argv[1])

    if not file_path.exists():
        print(f"File {file_path} not found...")
        return

    ext = file_path.suffix
    name = file_path.stem

    commands = {
        ".c": [f"gcc -Wall {file_path} -o {name}", f"./{name}"],
        ".cpp": [f"g++ -Wall {file_path} -o {name}", f"./{name}"],
        ".py": [f"python3 {file_path}"],
        ".rs": [f"rustc {file_path}", f"./{name}"],
        ".go": [f"go run {file_path}"],
        ".qmd": [f"quarto render {file_path}"]
    }

    if ext not in commands:
        print(f"Extention {ext} not supported")
        return

    for cmd in commands[ext]:
        print(f"-> Executing {cmd}")
        result = subprocess.run(cmd, shell = True)
        if result.returncode != 0:
            break

if __name__ == "__main__":
    run()
