#!/usr/bin/env python3 

import argparse
import subprocess
from pathlib import Path

def run():
    parser = argparse.ArgumentParser(description="Universal compiler and runner")
    parser.add_argument("file", nargs="?", help="File for running")
    parser.add_argument("-b", "--build", action="store_true", help="Build-only (Go/Haskell)")
    
    args = parser.parse_args()

    #Project Mode
    if Path("CMakeLists.txt").exists():
        print("--> CMake detected. Building...")
        subprocess.run("cmake -S . -B build && cmake --build build", shell=True)
        return

    if Path("Makefile").exists():
        print("--> Makefile detected. Initiating make...")
        subprocess.run("make", shell=True)
        return

    #Single File Mode
    if not args.file:
        print("Error: no file or no buildind instructions specified (Makefile/CMake).")
        return

    path = Path(args.file)
    if not path.exists():
        print(f"File {path} not found.")
        return

    ext = path.suffix
    name = path.stem

    # Logic
    match ext:
        case ".c" | "cpp":
            compiler = "gcc" if ext == ".c" else ".g++"
            cmd = f"{compiler} -Wall {path} -o {name} && ./{name}"

        case ".py":
            cmd = f"python3 {path}"

        case ".hs":
        # Haskell always requires compilation
            cmd = f"ghc --make {path} -o {name}"
            if not args.build:
            cmd += f" && ./{name}"

        case ".go":
            cmd = f"go build {path}" if args.build else f"go run {path}"

        case ".qmd":
            cmd = f"quarto render {path}"

        case _:
            print(f"Format {ext} not yet implemented")
            return

    print(f"--> Initiating: {cmd}")
    subprocess.run(cmd, shell=True)

if __name__ == "__main__":
    run()
